/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/BaseButton/BaseButton.vue')['default']
    BaseField: typeof import('./components/BaseField/BaseField.vue')['default']
    BaseLoader: typeof import('./components/BaseLoader/BaseLoader.vue')['default']
    CloseButton: typeof import('./components/CloseButton/CloseButton.vue')['default']
    GameCard: typeof import('./components/GameCard/GameCard.vue')['default']
    PasswordField: typeof import('./components/PasswordField/PasswordField.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./components/SvgIcon/SvgIcon.vue')['default']
    TheLoginForm: typeof import('./components/TheLoginForm/TheLoginForm.vue')['default']
    TheSidebar: typeof import('./components/TheSidebar/TheSidebar.vue')['default']
    TheToastList: typeof import('./components/TheToastList/TheToastList.vue')['default']
    TheToastListItem: typeof import('./components/TheToastList/TheToastListItem.vue')['default']
  }
}
