/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/BaseButton/BaseButton.vue')['default']
    BaseField: typeof import('./components/BaseField/BaseField.vue')['default']
    BaseLoader: typeof import('./components/BaseLoader/BaseLoader.vue')['default']
    CloseButton: typeof import('./components/CloseButton/CloseButton.vue')['default']
    GameCard: typeof import('./components/GameCard/GameCard.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    Loader: typeof import('./components/BaseLoader/Loader.vue')['default']
    PasswordField: typeof import('./components/PasswordField/PasswordField.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./components/SvgIcon/SvgIcon.vue')['default']
    TheLoginForm: typeof import('./components/TheLoginForm/TheLoginForm.vue')['default']
    TheSidebar: typeof import('./components/TheSidebar/TheSidebar.vue')['default']
    TheToastList: typeof import('./components/TheToastList/TheToastList.vue')['default']
    TheToastListItem: typeof import('./components/TheToastList/TheToastListItem.vue')['default']
    TheWelcome: typeof import('./components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
  }
}
